# Generated by Django 6.0.6 on 2026-08-03 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(help_text='Nome do curso', max_length=30)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(help_text='Nome da turma', max_length=5)),
                ('ano', models.PositiveSmallIntegerField(help_text='Ano da turma')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='core.curso')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turma',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.CharField(db_index=True, help_text='Matrícula do aluno', max_length=20, unique=True)),
                ('nome', models.CharField(help_text='Nome do aluno', max_length=70)),
                ('nascimento', models.DateField(help_text='Data de nascimento do aluno')),
                ('nome_responsavel', models.CharField(help_text='Nome do responsável pelo aluno', max_length=100)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso do aluno', max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Altura do aluno', max_digits=4, null=True)),
                ('medicamentos', models.TextField(blank=True, help_text='Medicamentos contínuos consumidos pelo aluno', null=True)),
                ('restricoes', models.TextField(blank=True, help_text='Restrições/Impedimentos médicos do aluno', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações internas sobre o aluno', null=True)),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Tipo sanguíneo do aluno', max_length=3, null=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turma')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'aluno',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.CharField(db_index=True, help_text='Matrícula do usuário', max_length=20, unique=True)),
                ('nascimento', models.DateField(help_text='Data de nascimento do usuário', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'ordering': ['matricula'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.DateField(help_text='Data do prontuário')),
                ('horario_inicio', models.TimeField(help_text='Horário de ínicio do prontuário')),
                ('horario_fim', models.TimeField(help_text='Horário de fim do prontuário')),
                ('descricao', models.TextField(help_text='Descrição do prontuário')),
                ('tipo_atendimento', models.CharField(choices=[('consulta', 'Consulta'), ('urgencia', 'Urgência'), ('medicacao', 'Medicação'), ('retorno', 'Retorno')], db_index=True, help_text='Tipo de atendimento do prontuário', max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('finalizado', 'Finalizado'), ('encaminhado', 'Encaminhado')], db_index=True, help_text='Status do prontuário', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='core.aluno')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
                'db_table': 'prontuario',
                'ordering': ['-data'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Declaracao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código da Declaracão', unique=True)),
                ('descricao', models.TextField(help_text='Descrição da Declaracão')),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='declaracoes', serialize=False, to='core.prontuario')),
                ('data_horario_emissao', models.DateTimeField(auto_now_add=True)),
                ('emitido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaracoes_emitidas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Declaração',
                'verbose_name_plural': 'Declarações',
                'db_table': 'declaracao',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
