# Generated by Django 6.0.6 on 2026-07-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracao',
            name='codigo',
            field=models.CharField(db_index=True, help_text='Código da Declaracão', max_length=64, unique=True),
        ),
    ]
